### ISSUE TITLE
Cannot run the demo code in your package(EnvExpInd)

### ISSUE THREAD

**Issue by bianleleren** [Spatial-R/EnvExpInd#1]
I am unable to execute this line of code in the fuction"get_reference_data_idw()" : first_date = "date" , the warning message is "**Error in get_refrence_data_idw(individual_data = individual_data_tem,  :  unused argument (frist_date = "date")**".
The very same problem occured when I run the function "get_refrence_data_krige(first_date = "date").
![erroe](https://user-images.githubusercontent.com/19194103/27510633-931bc840-5947-11e7-9872-6923550c2343.JPG)

I don't know how to fix that. I have installed all the packages required and make them loaded.

**Comment by Spatial-R** [comment]
Thanks. I have changed the codes in README file, you can try again. Make sure you know the idw and krige method before running the codes,  because additional parameters for the krige method need to be specified.
