### ISSUE TITLE
Problems about running the “exposure_estimate_simple” code!

### ISSUE THREAD

**Issue by bianleleren** [Spatial-R/EnvExpInd#3]
When I try to use your code on my own data, I kept getting this error: "Error in FUN(X[[i]], ...) : object 'date.targrt' not found". No matter how I chang the name of the date or the format of the variable, this warning just can't be solved. I'm sure my pollutant data has cover all the individual'date.
![qq 20170812022626](https://user-images.githubusercontent.com/19194103/29226949-8da1df50-7f06-11e7-8ed2-7ceceade272c.png)
![2](https://user-images.githubusercontent.com/19194103/29227021-cb3dfd76-7f06-11e7-8c39-d6f47e821b12.png)
![3](https://user-images.githubusercontent.com/19194103/29227030-d276cb0e-7f06-11e7-845a-df13cfa3972d.png)

**Comment by Spatial-R** [comment]
Hello, bianleleren, please show your dataset and codes. Because i can't find the answer to your question just on the pictures above.

**Comment by bianleleren** [comment]
Thank you so much for replying. Now I can only describe that problem to you because I am about to meet my deadline, so I have to delete that individual as to solve the problem. Actually there is only one observation which has caused this error. After I deleted it I can run your code successfully. I am sure there is nothing wrong with the data quality, this observation has its lat and lon and can be matched to a site, the pollutant data is also complete, however just can't get the simple estimation. Anyway, next time I find it I will submit all of it to you.
