### ISSUE TITLE
Problem about the "date" in EnvExpInd code!

### ISSUE THREAD

**Issue by bianleleren** [Spatial-R/EnvExpInd#4]

**Comment by bianleleren** [comment]
I have ran your code successfully before, but this time when I add some new weather data and pollutant data to my dataset，I cannt execute any of you estimate fuction and the error like this：
![image](https://user-images.githubusercontent.com/19194103/30242854-0332f75a-95d1-11e7-9382-f4472c67389c.png)
It seems the problem is about the date in the weather and pollutant data， but I am sure the date to be estimated has been fully covered.
![image](https://user-images.githubusercontent.com/19194103/30242861-4ddd2ba4-95d1-11e7-99f2-2db37dee7a5f.png)

**Comment by Spatial-R** [comment]
Thanks! You can predefine the value of each argument  in the  **expoure_estimate_simple** function (detailed codes for this function in [here](https://github.com/Spatial-R/EnvExpInd/blob/master/R/expoure_estimate_simple.R)) to test why you have got the error discussed above. I guess the problem may be on your dataset, do you have transformed all the columns with the data information into a standard formulation?

**Comment by bianleleren** [comment]
I'm sure I have transformed all the data into right type!
![image](https://user-images.githubusercontent.com/19194103/30248015-c0de2460-9652-11e7-96de-7b9b08cd1bd3.png)
![image](https://user-images.githubusercontent.com/19194103/30248022-e6e122c0-9652-11e7-9729-2239cdc24bd2.png)
![image](https://user-images.githubusercontent.com/19194103/30248072-dee794a4-9653-11e7-9229-a9d6d5efa85a.png)
![image](https://user-images.githubusercontent.com/19194103/30248304-b574bcce-9657-11e7-92f8-6e7c3e808887.png)

**Comment by Spatial-R** [comment]
Could you share your dataset with me? I think it is easier to find out the problem.

**Comment by bianleleren** [comment]
Alright, please check your email. I want to get the simple estimation of the individual's temperature exposure for ten days before the "date" variable in the dataset.

**Comment by huanhuan118** [comment]
Warning messages:
1: In FUN(newX[, i], ...) : NAs introduced by coercion
2: In FUN(newX[, i], ...) : NAs introduced by coercion
I ran your data step by step, but  there are two Warning messages, what is wrong?
